name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    # 1. Clonar el repositorio
    - uses: actions/checkout@v4

    # 2. Configurar Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json

    # 3. Instalar dependencias
    - run: npm ci

    # 4. Compilar el proyecto
    - name: Build
      run: npm run build

    # 5. Guardar los resultados de la compilación como artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build/ # Cambiar "build/" según tu directorio de compilación

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el artifact generado en el paso de build
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: ./build/

    # 2. Loguearse en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir la imagen Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nombre-imagen:latest ./build/

    # 4. Subir la imagen a Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nombre-imagen:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el artifact generado
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: ./deployed-artifact/

    # 2. Realizar el despliegue
    - name: Deploy artifact
      run: echo "Deploying artifact from ./deployed-artifact/"
